INSERT INTO
	matching.Match
	( 
	MatchId,
    SubmitterEmail,
    ReceivedDate,
    Status,
    InputData,
    ResultData,
	ExternalLookupResults,
	IsServiceMediated,
	ApiKey,
	Error,
	DoExternalLookup
	)
VALUES 
	(
	@MatchId,
    @SubmitterEmail,
    @ReceivedDate,
    @Status,
    @InputData,
    @ResultData,
	@ExternalLookupResults,
	@IsServiceMediated,
	@ApiKey,
	@Error,
	@DoExternalLookup
	)