CREATE TABLE [darwincore].[Taxon] (
    [TaxonID]                  nvarchar (1000) NOT NULL,
    [ScientificNameID]         NVARCHAR (1000)  NULL,
    [AcceptedNameUsageID]      NVARCHAR (1000)  NULL,
    [ParentNameUsageID]        NVARCHAR (1000)  NULL,
    [OriginalNameUsageID]      NVARCHAR (1000)  NULL,
    [NameAccordingToID]        NVARCHAR (1000)  NULL,
    [NamePublishedInID]        NVARCHAR (1000)  NULL,
    [TaxonConceptID]           NVARCHAR (1000)  NULL,
    [ScientificName]           NVARCHAR (2000)  NULL,
    [AcceptedNameUsage]        NVARCHAR (2000)  NULL,
    [ParentNameUsage]          NVARCHAR (2000)  NULL,
    [OriginalNameUsage]        NVARCHAR (2000)  NULL,
    [NameAccordingTo]          NVARCHAR (2000)  NULL,
    [NamePublishedIn]          NVARCHAR (2000)  NULL,
    [HigherClassification]     NVARCHAR (2000)  NULL,
    [Kingdom]                  NVARCHAR (1000)  NULL,
    [Phylum]                   NVARCHAR (1000)  NULL,
    [Class]                    NVARCHAR (1000)  NULL,
    [Order]                    NVARCHAR (1000)  NULL,
    [Family]                   NVARCHAR (1000)  NULL,
    [Genus]                    NVARCHAR (1000)  NULL,
    [SubGenus]                 NVARCHAR (1000)  NULL,
    [SpecificEpithet]          NVARCHAR (1000)  NULL,
    [InfraspecificEpithet]     NVARCHAR (1000)  NULL,
    [TaxonRank]                NVARCHAR (1000)  NULL,
    [VerbatimTaxonRank]        NVARCHAR (1000)  NULL,
    [ScientificNameAuthorship] NVARCHAR (1000)  NULL,
    [VernacularName]           NVARCHAR (1000)  NULL,
    [NomenclaturalCode]        NVARCHAR (1000)  NULL,
    [TaxonomicStatus]          NVARCHAR (1000)  NULL,
    [NomenclaturalStatus]      NVARCHAR (1000)  NULL,
    [TaxonRemarks]             NVARCHAR (2000)  NULL,
    [Modified]                 DATETIME         NULL,
    [Rights]                   NVARCHAR (2000)  NULL,
    [RightsHolder]             NVARCHAR (1000)  NULL,
    [AccessRights]             NVARCHAR (2000)  NULL,
    [BibliographicCitation]    NVARCHAR (2000)  NULL,
    [InformationWitheld]       NVARCHAR (2000)  NULL,
    [DatasetID]                NVARCHAR (1000)  NULL,
    [DatasetName]              NVARCHAR (1000)  NULL,
    [Source]                   NVARCHAR (1000)  NULL,
    PRIMARY KEY CLUSTERED ([TaxonID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

