ALTER TABLE [admin].[DataType]
    ADD CONSTRAINT [prkDataType] PRIMARY KEY CLUSTERED ([DataTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

