//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("NZOR_System", "FK_GeoRegion_GeoRegionSchema", "GeoRegionSchema", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NZOR.Data.SystemData.GeoRegionSchema), "GeoRegion", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NZOR.Data.SystemData.GeoRegion))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("NZOR_System", "FK_NameClassProperty_NameClass", "NameClass", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NZOR.Data.SystemData.NameClass), "NameClassProperty", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NZOR.Data.SystemData.NameClassProperty))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("NZOR_System", "FK_TaxonPropertyType_TaxonPropertyClass", "TaxonPropertyClass", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NZOR.Data.SystemData.TaxonPropertyClass), "TaxonPropertyType", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NZOR.Data.SystemData.TaxonPropertyType))]

// Original file name:
// Generation date: 28/04/2010 12:56:05 p.m.
namespace NZOR.Data.SystemData
{
    
    /// <summary>
    /// There are no comments for Entities in the schema.
    /// </summary>
    public partial class Entities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : 
                base("name=Entities", "Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : 
                base(connectionString, "Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "Entities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for ConceptRelationshipType in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ConceptRelationshipType> ConceptRelationshipType
        {
            get
            {
                if ((this._ConceptRelationshipType == null))
                {
                    this._ConceptRelationshipType = base.CreateQuery<ConceptRelationshipType>("[ConceptRelationshipType]");
                }
                return this._ConceptRelationshipType;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ConceptRelationshipType> _ConceptRelationshipType;
        /// <summary>
        /// There are no comments for GeoRegion in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<GeoRegion> GeoRegion
        {
            get
            {
                if ((this._GeoRegion == null))
                {
                    this._GeoRegion = base.CreateQuery<GeoRegion>("[GeoRegion]");
                }
                return this._GeoRegion;
            }
        }
        private global::System.Data.Objects.ObjectQuery<GeoRegion> _GeoRegion;
        /// <summary>
        /// There are no comments for GeoRegionSchema in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<GeoRegionSchema> GeoRegionSchema
        {
            get
            {
                if ((this._GeoRegionSchema == null))
                {
                    this._GeoRegionSchema = base.CreateQuery<GeoRegionSchema>("[GeoRegionSchema]");
                }
                return this._GeoRegionSchema;
            }
        }
        private global::System.Data.Objects.ObjectQuery<GeoRegionSchema> _GeoRegionSchema;
        /// <summary>
        /// There are no comments for Match in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Match> Match
        {
            get
            {
                if ((this._Match == null))
                {
                    this._Match = base.CreateQuery<Match>("[Match]");
                }
                return this._Match;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Match> _Match;
        /// <summary>
        /// There are no comments for NameClass in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<NameClass> NameClass
        {
            get
            {
                if ((this._NameClass == null))
                {
                    this._NameClass = base.CreateQuery<NameClass>("[NameClass]");
                }
                return this._NameClass;
            }
        }
        private global::System.Data.Objects.ObjectQuery<NameClass> _NameClass;
        /// <summary>
        /// There are no comments for NameClassProperty in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<NameClassProperty> NameClassProperty
        {
            get
            {
                if ((this._NameClassProperty == null))
                {
                    this._NameClassProperty = base.CreateQuery<NameClassProperty>("[NameClassProperty]");
                }
                return this._NameClassProperty;
            }
        }
        private global::System.Data.Objects.ObjectQuery<NameClassProperty> _NameClassProperty;
        /// <summary>
        /// There are no comments for NamePropertyLookup in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<NamePropertyLookup> NamePropertyLookup
        {
            get
            {
                if ((this._NamePropertyLookup == null))
                {
                    this._NamePropertyLookup = base.CreateQuery<NamePropertyLookup>("[NamePropertyLookup]");
                }
                return this._NamePropertyLookup;
            }
        }
        private global::System.Data.Objects.ObjectQuery<NamePropertyLookup> _NamePropertyLookup;
        /// <summary>
        /// There are no comments for Provider in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Provider> Provider
        {
            get
            {
                if ((this._Provider == null))
                {
                    this._Provider = base.CreateQuery<Provider>("[Provider]");
                }
                return this._Provider;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Provider> _Provider;
        /// <summary>
        /// There are no comments for TaxonPropertyClass in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<TaxonPropertyClass> TaxonPropertyClass
        {
            get
            {
                if ((this._TaxonPropertyClass == null))
                {
                    this._TaxonPropertyClass = base.CreateQuery<TaxonPropertyClass>("[TaxonPropertyClass]");
                }
                return this._TaxonPropertyClass;
            }
        }
        private global::System.Data.Objects.ObjectQuery<TaxonPropertyClass> _TaxonPropertyClass;
        /// <summary>
        /// There are no comments for TaxonPropertyLookup in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<TaxonPropertyLookup> TaxonPropertyLookup
        {
            get
            {
                if ((this._TaxonPropertyLookup == null))
                {
                    this._TaxonPropertyLookup = base.CreateQuery<TaxonPropertyLookup>("[TaxonPropertyLookup]");
                }
                return this._TaxonPropertyLookup;
            }
        }
        private global::System.Data.Objects.ObjectQuery<TaxonPropertyLookup> _TaxonPropertyLookup;
        /// <summary>
        /// There are no comments for TaxonPropertyType in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<TaxonPropertyType> TaxonPropertyType
        {
            get
            {
                if ((this._TaxonPropertyType == null))
                {
                    this._TaxonPropertyType = base.CreateQuery<TaxonPropertyType>("[TaxonPropertyType]");
                }
                return this._TaxonPropertyType;
            }
        }
        private global::System.Data.Objects.ObjectQuery<TaxonPropertyType> _TaxonPropertyType;
        /// <summary>
        /// There are no comments for TaxonRank in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<TaxonRank> TaxonRank
        {
            get
            {
                if ((this._TaxonRank == null))
                {
                    this._TaxonRank = base.CreateQuery<TaxonRank>("[TaxonRank]");
                }
                return this._TaxonRank;
            }
        }
        private global::System.Data.Objects.ObjectQuery<TaxonRank> _TaxonRank;
        /// <summary>
        /// There are no comments for ConceptRelationshipType in the schema.
        /// </summary>
        public void AddToConceptRelationshipType(ConceptRelationshipType conceptRelationshipType)
        {
            base.AddObject("ConceptRelationshipType", conceptRelationshipType);
        }
        /// <summary>
        /// There are no comments for GeoRegion in the schema.
        /// </summary>
        public void AddToGeoRegion(GeoRegion geoRegion)
        {
            base.AddObject("GeoRegion", geoRegion);
        }
        /// <summary>
        /// There are no comments for GeoRegionSchema in the schema.
        /// </summary>
        public void AddToGeoRegionSchema(GeoRegionSchema geoRegionSchema)
        {
            base.AddObject("GeoRegionSchema", geoRegionSchema);
        }
        /// <summary>
        /// There are no comments for Match in the schema.
        /// </summary>
        public void AddToMatch(Match match)
        {
            base.AddObject("Match", match);
        }
        /// <summary>
        /// There are no comments for NameClass in the schema.
        /// </summary>
        public void AddToNameClass(NameClass nameClass)
        {
            base.AddObject("NameClass", nameClass);
        }
        /// <summary>
        /// There are no comments for NameClassProperty in the schema.
        /// </summary>
        public void AddToNameClassProperty(NameClassProperty nameClassProperty)
        {
            base.AddObject("NameClassProperty", nameClassProperty);
        }
        /// <summary>
        /// There are no comments for NamePropertyLookup in the schema.
        /// </summary>
        public void AddToNamePropertyLookup(NamePropertyLookup namePropertyLookup)
        {
            base.AddObject("NamePropertyLookup", namePropertyLookup);
        }
        /// <summary>
        /// There are no comments for Provider in the schema.
        /// </summary>
        public void AddToProvider(Provider provider)
        {
            base.AddObject("Provider", provider);
        }
        /// <summary>
        /// There are no comments for TaxonPropertyClass in the schema.
        /// </summary>
        public void AddToTaxonPropertyClass(TaxonPropertyClass taxonPropertyClass)
        {
            base.AddObject("TaxonPropertyClass", taxonPropertyClass);
        }
        /// <summary>
        /// There are no comments for TaxonPropertyLookup in the schema.
        /// </summary>
        public void AddToTaxonPropertyLookup(TaxonPropertyLookup taxonPropertyLookup)
        {
            base.AddObject("TaxonPropertyLookup", taxonPropertyLookup);
        }
        /// <summary>
        /// There are no comments for TaxonPropertyType in the schema.
        /// </summary>
        public void AddToTaxonPropertyType(TaxonPropertyType taxonPropertyType)
        {
            base.AddObject("TaxonPropertyType", taxonPropertyType);
        }
        /// <summary>
        /// There are no comments for TaxonRank in the schema.
        /// </summary>
        public void AddToTaxonRank(TaxonRank taxonRank)
        {
            base.AddObject("TaxonRank", taxonRank);
        }
    }
    /// <summary>
    /// There are no comments for NZOR_System.ConceptRelationshipType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ConceptRelationshipTypeID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NZOR_System", Name="ConceptRelationshipType")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ConceptRelationshipType : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ConceptRelationshipType object.
        /// </summary>
        /// <param name="conceptRelationshipTypeID">Initial value of ConceptRelationshipTypeID.</param>
        /// <param name="relationship">Initial value of Relationship.</param>
        public static ConceptRelationshipType CreateConceptRelationshipType(global::System.Guid conceptRelationshipTypeID, string relationship)
        {
            ConceptRelationshipType conceptRelationshipType = new ConceptRelationshipType();
            conceptRelationshipType.ConceptRelationshipTypeID = conceptRelationshipTypeID;
            conceptRelationshipType.Relationship = relationship;
            return conceptRelationshipType;
        }
        /// <summary>
        /// There are no comments for Property ConceptRelationshipTypeID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ConceptRelationshipTypeID
        {
            get
            {
                return this._ConceptRelationshipTypeID;
            }
            set
            {
                this.OnConceptRelationshipTypeIDChanging(value);
                this.ReportPropertyChanging("ConceptRelationshipTypeID");
                this._ConceptRelationshipTypeID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ConceptRelationshipTypeID");
                this.OnConceptRelationshipTypeIDChanged();
            }
        }
        private global::System.Guid _ConceptRelationshipTypeID;
        partial void OnConceptRelationshipTypeIDChanging(global::System.Guid value);
        partial void OnConceptRelationshipTypeIDChanged();
        /// <summary>
        /// There are no comments for Property Relationship in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Relationship
        {
            get
            {
                return this._Relationship;
            }
            set
            {
                this.OnRelationshipChanging(value);
                this.ReportPropertyChanging("Relationship");
                this._Relationship = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Relationship");
                this.OnRelationshipChanged();
            }
        }
        private string _Relationship;
        partial void OnRelationshipChanging(string value);
        partial void OnRelationshipChanged();
        /// <summary>
        /// There are no comments for Property MinOccurences in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> MinOccurences
        {
            get
            {
                return this._MinOccurences;
            }
            set
            {
                this.OnMinOccurencesChanging(value);
                this.ReportPropertyChanging("MinOccurences");
                this._MinOccurences = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MinOccurences");
                this.OnMinOccurencesChanged();
            }
        }
        private global::System.Nullable<int> _MinOccurences;
        partial void OnMinOccurencesChanging(global::System.Nullable<int> value);
        partial void OnMinOccurencesChanged();
        /// <summary>
        /// There are no comments for Property MaxOccurrences in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> MaxOccurrences
        {
            get
            {
                return this._MaxOccurrences;
            }
            set
            {
                this.OnMaxOccurrencesChanging(value);
                this.ReportPropertyChanging("MaxOccurrences");
                this._MaxOccurrences = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MaxOccurrences");
                this.OnMaxOccurrencesChanged();
            }
        }
        private global::System.Nullable<int> _MaxOccurrences;
        partial void OnMaxOccurrencesChanging(global::System.Nullable<int> value);
        partial void OnMaxOccurrencesChanged();
    }
    /// <summary>
    /// There are no comments for NZOR_System.GeoRegion in the schema.
    /// </summary>
    /// <KeyProperties>
    /// GeoRegionID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NZOR_System", Name="GeoRegion")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class GeoRegion : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new GeoRegion object.
        /// </summary>
        /// <param name="geoRegionID">Initial value of GeoRegionID.</param>
        /// <param name="regionName">Initial value of RegionName.</param>
        public static GeoRegion CreateGeoRegion(global::System.Guid geoRegionID, string regionName)
        {
            GeoRegion geoRegion = new GeoRegion();
            geoRegion.GeoRegionID = geoRegionID;
            geoRegion.RegionName = regionName;
            return geoRegion;
        }
        /// <summary>
        /// There are no comments for Property GeoRegionID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid GeoRegionID
        {
            get
            {
                return this._GeoRegionID;
            }
            set
            {
                this.OnGeoRegionIDChanging(value);
                this.ReportPropertyChanging("GeoRegionID");
                this._GeoRegionID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("GeoRegionID");
                this.OnGeoRegionIDChanged();
            }
        }
        private global::System.Guid _GeoRegionID;
        partial void OnGeoRegionIDChanging(global::System.Guid value);
        partial void OnGeoRegionIDChanged();
        /// <summary>
        /// There are no comments for Property RegionName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionName
        {
            get
            {
                return this._RegionName;
            }
            set
            {
                this.OnRegionNameChanging(value);
                this.ReportPropertyChanging("RegionName");
                this._RegionName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("RegionName");
                this.OnRegionNameChanged();
            }
        }
        private string _RegionName;
        partial void OnRegionNameChanging(string value);
        partial void OnRegionNameChanged();
        /// <summary>
        /// There are no comments for Property Language in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this._Language;
            }
            set
            {
                this.OnLanguageChanging(value);
                this.ReportPropertyChanging("Language");
                this._Language = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Language");
                this.OnLanguageChanged();
            }
        }
        private string _Language;
        partial void OnLanguageChanging(string value);
        partial void OnLanguageChanged();
        /// <summary>
        /// There are no comments for Property CorrectRegionID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.Guid> CorrectRegionID
        {
            get
            {
                return this._CorrectRegionID;
            }
            set
            {
                this.OnCorrectRegionIDChanging(value);
                this.ReportPropertyChanging("CorrectRegionID");
                this._CorrectRegionID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CorrectRegionID");
                this.OnCorrectRegionIDChanged();
            }
        }
        private global::System.Nullable<global::System.Guid> _CorrectRegionID;
        partial void OnCorrectRegionIDChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnCorrectRegionIDChanged();
        /// <summary>
        /// There are no comments for Property ParentRegionID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.Guid> ParentRegionID
        {
            get
            {
                return this._ParentRegionID;
            }
            set
            {
                this.OnParentRegionIDChanging(value);
                this.ReportPropertyChanging("ParentRegionID");
                this._ParentRegionID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ParentRegionID");
                this.OnParentRegionIDChanged();
            }
        }
        private global::System.Nullable<global::System.Guid> _ParentRegionID;
        partial void OnParentRegionIDChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnParentRegionIDChanged();
        /// <summary>
        /// There are no comments for GeoRegionSchema in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NZOR_System", "FK_GeoRegion_GeoRegionSchema", "GeoRegionSchema")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public GeoRegionSchema GeoRegionSchema
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<GeoRegionSchema>("NZOR_System.FK_GeoRegion_GeoRegionSchema", "GeoRegionSchema").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<GeoRegionSchema>("NZOR_System.FK_GeoRegion_GeoRegionSchema", "GeoRegionSchema").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for GeoRegionSchema in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<GeoRegionSchema> GeoRegionSchemaReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<GeoRegionSchema>("NZOR_System.FK_GeoRegion_GeoRegionSchema", "GeoRegionSchema");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<GeoRegionSchema>("NZOR_System.FK_GeoRegion_GeoRegionSchema", "GeoRegionSchema", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for NZOR_System.GeoRegionSchema in the schema.
    /// </summary>
    /// <KeyProperties>
    /// GeoRegionSchemaID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NZOR_System", Name="GeoRegionSchema")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class GeoRegionSchema : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new GeoRegionSchema object.
        /// </summary>
        /// <param name="geoRegionSchemaID">Initial value of GeoRegionSchemaID.</param>
        /// <param name="schemaName">Initial value of SchemaName.</param>
        public static GeoRegionSchema CreateGeoRegionSchema(global::System.Guid geoRegionSchemaID, string schemaName)
        {
            GeoRegionSchema geoRegionSchema = new GeoRegionSchema();
            geoRegionSchema.GeoRegionSchemaID = geoRegionSchemaID;
            geoRegionSchema.SchemaName = schemaName;
            return geoRegionSchema;
        }
        /// <summary>
        /// There are no comments for Property GeoRegionSchemaID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid GeoRegionSchemaID
        {
            get
            {
                return this._GeoRegionSchemaID;
            }
            set
            {
                this.OnGeoRegionSchemaIDChanging(value);
                this.ReportPropertyChanging("GeoRegionSchemaID");
                this._GeoRegionSchemaID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("GeoRegionSchemaID");
                this.OnGeoRegionSchemaIDChanged();
            }
        }
        private global::System.Guid _GeoRegionSchemaID;
        partial void OnGeoRegionSchemaIDChanging(global::System.Guid value);
        partial void OnGeoRegionSchemaIDChanged();
        /// <summary>
        /// There are no comments for Property SchemaName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SchemaName
        {
            get
            {
                return this._SchemaName;
            }
            set
            {
                this.OnSchemaNameChanging(value);
                this.ReportPropertyChanging("SchemaName");
                this._SchemaName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SchemaName");
                this.OnSchemaNameChanged();
            }
        }
        private string _SchemaName;
        partial void OnSchemaNameChanging(string value);
        partial void OnSchemaNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for GeoRegion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NZOR_System", "FK_GeoRegion_GeoRegionSchema", "GeoRegion")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<GeoRegion> GeoRegion
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<GeoRegion>("NZOR_System.FK_GeoRegion_GeoRegionSchema", "GeoRegion");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<GeoRegion>("NZOR_System.FK_GeoRegion_GeoRegionSchema", "GeoRegion", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for NZOR_System.Match in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MatchPk
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NZOR_System", Name="Match")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Match : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Match object.
        /// </summary>
        /// <param name="matchPk">Initial value of MatchPk.</param>
        public static Match CreateMatch(int matchPk)
        {
            Match match = new Match();
            match.MatchPk = matchPk;
            return match;
        }
        /// <summary>
        /// There are no comments for Property MatchPk in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchPk
        {
            get
            {
                return this._MatchPk;
            }
            set
            {
                this.OnMatchPkChanging(value);
                this.ReportPropertyChanging("MatchPk");
                this._MatchPk = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MatchPk");
                this.OnMatchPkChanged();
            }
        }
        private int _MatchPk;
        partial void OnMatchPkChanging(int value);
        partial void OnMatchPkChanged();
        /// <summary>
        /// There are no comments for Property MatchRuleSet in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string MatchRuleSet
        {
            get
            {
                return this._MatchRuleSet;
            }
            set
            {
                this.OnMatchRuleSetChanging(value);
                this.ReportPropertyChanging("MatchRuleSet");
                this._MatchRuleSet = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("MatchRuleSet");
                this.OnMatchRuleSetChanged();
            }
        }
        private string _MatchRuleSet;
        partial void OnMatchRuleSetChanging(string value);
        partial void OnMatchRuleSetChanged();
        /// <summary>
        /// There are no comments for Property MatchFirst in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> MatchFirst
        {
            get
            {
                return this._MatchFirst;
            }
            set
            {
                this.OnMatchFirstChanging(value);
                this.ReportPropertyChanging("MatchFirst");
                this._MatchFirst = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MatchFirst");
                this.OnMatchFirstChanged();
            }
        }
        private global::System.Nullable<bool> _MatchFirst;
        partial void OnMatchFirstChanging(global::System.Nullable<bool> value);
        partial void OnMatchFirstChanged();
        /// <summary>
        /// There are no comments for Property MatchFunction in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string MatchFunction
        {
            get
            {
                return this._MatchFunction;
            }
            set
            {
                this.OnMatchFunctionChanging(value);
                this.ReportPropertyChanging("MatchFunction");
                this._MatchFunction = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("MatchFunction");
                this.OnMatchFunctionChanged();
            }
        }
        private string _MatchFunction;
        partial void OnMatchFunctionChanging(string value);
        partial void OnMatchFunctionChanged();
        /// <summary>
        /// There are no comments for Property MatchThreshold in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> MatchThreshold
        {
            get
            {
                return this._MatchThreshold;
            }
            set
            {
                this.OnMatchThresholdChanging(value);
                this.ReportPropertyChanging("MatchThreshold");
                this._MatchThreshold = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MatchThreshold");
                this.OnMatchThresholdChanged();
            }
        }
        private global::System.Nullable<int> _MatchThreshold;
        partial void OnMatchThresholdChanging(global::System.Nullable<int> value);
        partial void OnMatchThresholdChanged();
        /// <summary>
        /// There are no comments for Property MatchPassFk in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> MatchPassFk
        {
            get
            {
                return this._MatchPassFk;
            }
            set
            {
                this.OnMatchPassFkChanging(value);
                this.ReportPropertyChanging("MatchPassFk");
                this._MatchPassFk = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MatchPassFk");
                this.OnMatchPassFkChanged();
            }
        }
        private global::System.Nullable<int> _MatchPassFk;
        partial void OnMatchPassFkChanging(global::System.Nullable<int> value);
        partial void OnMatchPassFkChanged();
        /// <summary>
        /// There are no comments for Property MatchFailFk in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> MatchFailFk
        {
            get
            {
                return this._MatchFailFk;
            }
            set
            {
                this.OnMatchFailFkChanging(value);
                this.ReportPropertyChanging("MatchFailFk");
                this._MatchFailFk = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MatchFailFk");
                this.OnMatchFailFkChanged();
            }
        }
        private global::System.Nullable<int> _MatchFailFk;
        partial void OnMatchFailFkChanging(global::System.Nullable<int> value);
        partial void OnMatchFailFkChanged();
    }
    /// <summary>
    /// There are no comments for NZOR_System.NameClass in the schema.
    /// </summary>
    /// <KeyProperties>
    /// NameClassID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NZOR_System", Name="NameClass")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class NameClass : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new NameClass object.
        /// </summary>
        /// <param name="nameClassID">Initial value of NameClassID.</param>
        /// <param name="title">Initial value of Title.</param>
        public static NameClass CreateNameClass(global::System.Guid nameClassID, string title)
        {
            NameClass nameClass = new NameClass();
            nameClass.NameClassID = nameClassID;
            nameClass.Title = title;
            return nameClass;
        }
        /// <summary>
        /// There are no comments for Property NameClassID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid NameClassID
        {
            get
            {
                return this._NameClassID;
            }
            set
            {
                this.OnNameClassIDChanging(value);
                this.ReportPropertyChanging("NameClassID");
                this._NameClassID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NameClassID");
                this.OnNameClassIDChanged();
            }
        }
        private global::System.Guid _NameClassID;
        partial void OnNameClassIDChanging(global::System.Guid value);
        partial void OnNameClassIDChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for NameClassProperty in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NZOR_System", "FK_NameClassProperty_NameClass", "NameClassProperty")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<NameClassProperty> NameClassProperty
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<NameClassProperty>("NZOR_System.FK_NameClassProperty_NameClass", "NameClassProperty");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<NameClassProperty>("NZOR_System.FK_NameClassProperty_NameClass", "NameClassProperty", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for NZOR_System.NameClassProperty in the schema.
    /// </summary>
    /// <KeyProperties>
    /// NameClassPropertyID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NZOR_System", Name="NameClassProperty")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class NameClassProperty : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new NameClassProperty object.
        /// </summary>
        /// <param name="nameClassPropertyID">Initial value of NameClassPropertyID.</param>
        public static NameClassProperty CreateNameClassProperty(global::System.Guid nameClassPropertyID)
        {
            NameClassProperty nameClassProperty = new NameClassProperty();
            nameClassProperty.NameClassPropertyID = nameClassPropertyID;
            return nameClassProperty;
        }
        /// <summary>
        /// There are no comments for Property NameClassPropertyID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid NameClassPropertyID
        {
            get
            {
                return this._NameClassPropertyID;
            }
            set
            {
                this.OnNameClassPropertyIDChanging(value);
                this.ReportPropertyChanging("NameClassPropertyID");
                this._NameClassPropertyID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NameClassPropertyID");
                this.OnNameClassPropertyIDChanged();
            }
        }
        private global::System.Guid _NameClassPropertyID;
        partial void OnNameClassPropertyIDChanging(global::System.Guid value);
        partial void OnNameClassPropertyIDChanged();
        /// <summary>
        /// There are no comments for Property PropertyName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyName
        {
            get
            {
                return this._PropertyName;
            }
            set
            {
                this.OnPropertyNameChanging(value);
                this.ReportPropertyChanging("PropertyName");
                this._PropertyName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PropertyName");
                this.OnPropertyNameChanged();
            }
        }
        private string _PropertyName;
        partial void OnPropertyNameChanging(string value);
        partial void OnPropertyNameChanged();
        /// <summary>
        /// There are no comments for Property PropertyType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyType
        {
            get
            {
                return this._PropertyType;
            }
            set
            {
                this.OnPropertyTypeChanging(value);
                this.ReportPropertyChanging("PropertyType");
                this._PropertyType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PropertyType");
                this.OnPropertyTypeChanged();
            }
        }
        private string _PropertyType;
        partial void OnPropertyTypeChanging(string value);
        partial void OnPropertyTypeChanged();
        /// <summary>
        /// There are no comments for Property MinOccurrences in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> MinOccurrences
        {
            get
            {
                return this._MinOccurrences;
            }
            set
            {
                this.OnMinOccurrencesChanging(value);
                this.ReportPropertyChanging("MinOccurrences");
                this._MinOccurrences = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MinOccurrences");
                this.OnMinOccurrencesChanged();
            }
        }
        private global::System.Nullable<int> _MinOccurrences;
        partial void OnMinOccurrencesChanging(global::System.Nullable<int> value);
        partial void OnMinOccurrencesChanged();
        /// <summary>
        /// There are no comments for Property MaxOccurrences in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> MaxOccurrences
        {
            get
            {
                return this._MaxOccurrences;
            }
            set
            {
                this.OnMaxOccurrencesChanging(value);
                this.ReportPropertyChanging("MaxOccurrences");
                this._MaxOccurrences = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MaxOccurrences");
                this.OnMaxOccurrencesChanged();
            }
        }
        private global::System.Nullable<int> _MaxOccurrences;
        partial void OnMaxOccurrencesChanging(global::System.Nullable<int> value);
        partial void OnMaxOccurrencesChanged();
        /// <summary>
        /// There are no comments for Property GoverningCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string GoverningCode
        {
            get
            {
                return this._GoverningCode;
            }
            set
            {
                this.OnGoverningCodeChanging(value);
                this.ReportPropertyChanging("GoverningCode");
                this._GoverningCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("GoverningCode");
                this.OnGoverningCodeChanged();
            }
        }
        private string _GoverningCode;
        partial void OnGoverningCodeChanging(string value);
        partial void OnGoverningCodeChanged();
        /// <summary>
        /// There are no comments for NameClass in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NZOR_System", "FK_NameClassProperty_NameClass", "NameClass")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public NameClass NameClass
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<NameClass>("NZOR_System.FK_NameClassProperty_NameClass", "NameClass").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<NameClass>("NZOR_System.FK_NameClassProperty_NameClass", "NameClass").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for NameClass in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<NameClass> NameClassReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<NameClass>("NZOR_System.FK_NameClassProperty_NameClass", "NameClass");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<NameClass>("NZOR_System.FK_NameClassProperty_NameClass", "NameClass", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for NZOR_System.NamePropertyLookup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// NamePropertyLookupID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NZOR_System", Name="NamePropertyLookup")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class NamePropertyLookup : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new NamePropertyLookup object.
        /// </summary>
        /// <param name="namePropertyLookupID">Initial value of NamePropertyLookupID.</param>
        /// <param name="nameClassPropertyID">Initial value of NameClassPropertyID.</param>
        public static NamePropertyLookup CreateNamePropertyLookup(global::System.Guid namePropertyLookupID, global::System.Guid nameClassPropertyID)
        {
            NamePropertyLookup namePropertyLookup = new NamePropertyLookup();
            namePropertyLookup.NamePropertyLookupID = namePropertyLookupID;
            namePropertyLookup.NameClassPropertyID = nameClassPropertyID;
            return namePropertyLookup;
        }
        /// <summary>
        /// There are no comments for Property NamePropertyLookupID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid NamePropertyLookupID
        {
            get
            {
                return this._NamePropertyLookupID;
            }
            set
            {
                this.OnNamePropertyLookupIDChanging(value);
                this.ReportPropertyChanging("NamePropertyLookupID");
                this._NamePropertyLookupID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NamePropertyLookupID");
                this.OnNamePropertyLookupIDChanged();
            }
        }
        private global::System.Guid _NamePropertyLookupID;
        partial void OnNamePropertyLookupIDChanging(global::System.Guid value);
        partial void OnNamePropertyLookupIDChanged();
        /// <summary>
        /// There are no comments for Property NameClassPropertyID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid NameClassPropertyID
        {
            get
            {
                return this._NameClassPropertyID;
            }
            set
            {
                this.OnNameClassPropertyIDChanging(value);
                this.ReportPropertyChanging("NameClassPropertyID");
                this._NameClassPropertyID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NameClassPropertyID");
                this.OnNameClassPropertyIDChanged();
            }
        }
        private global::System.Guid _NameClassPropertyID;
        partial void OnNameClassPropertyIDChanging(global::System.Guid value);
        partial void OnNameClassPropertyIDChanged();
        /// <summary>
        /// There are no comments for Property ParentLoookupID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.Guid> ParentLoookupID
        {
            get
            {
                return this._ParentLoookupID;
            }
            set
            {
                this.OnParentLoookupIDChanging(value);
                this.ReportPropertyChanging("ParentLoookupID");
                this._ParentLoookupID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ParentLoookupID");
                this.OnParentLoookupIDChanged();
            }
        }
        private global::System.Nullable<global::System.Guid> _ParentLoookupID;
        partial void OnParentLoookupIDChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnParentLoookupIDChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this.ReportPropertyChanging("Value");
                this._Value = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Value");
                this.OnValueChanged();
            }
        }
        private string _Value;
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Property AlternativeStrings in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AlternativeStrings
        {
            get
            {
                return this._AlternativeStrings;
            }
            set
            {
                this.OnAlternativeStringsChanging(value);
                this.ReportPropertyChanging("AlternativeStrings");
                this._AlternativeStrings = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("AlternativeStrings");
                this.OnAlternativeStringsChanged();
            }
        }
        private string _AlternativeStrings;
        partial void OnAlternativeStringsChanging(string value);
        partial void OnAlternativeStringsChanged();
        /// <summary>
        /// There are no comments for Property SortOrder in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> SortOrder
        {
            get
            {
                return this._SortOrder;
            }
            set
            {
                this.OnSortOrderChanging(value);
                this.ReportPropertyChanging("SortOrder");
                this._SortOrder = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SortOrder");
                this.OnSortOrderChanged();
            }
        }
        private global::System.Nullable<int> _SortOrder;
        partial void OnSortOrderChanging(global::System.Nullable<int> value);
        partial void OnSortOrderChanged();
    }
    /// <summary>
    /// There are no comments for NZOR_System.Provider in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProviderID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NZOR_System", Name="Provider")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Provider : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Provider object.
        /// </summary>
        /// <param name="providerID">Initial value of ProviderID.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Provider CreateProvider(global::System.Guid providerID, string name)
        {
            Provider provider = new Provider();
            provider.ProviderID = providerID;
            provider.Name = name;
            return provider;
        }
        /// <summary>
        /// There are no comments for Property ProviderID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ProviderID
        {
            get
            {
                return this._ProviderID;
            }
            set
            {
                this.OnProviderIDChanging(value);
                this.ReportPropertyChanging("ProviderID");
                this._ProviderID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProviderID");
                this.OnProviderIDChanged();
            }
        }
        private global::System.Guid _ProviderID;
        partial void OnProviderIDChanging(global::System.Guid value);
        partial void OnProviderIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
    /// <summary>
    /// There are no comments for NZOR_System.TaxonPropertyClass in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TaxonPropertyClassID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NZOR_System", Name="TaxonPropertyClass")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TaxonPropertyClass : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TaxonPropertyClass object.
        /// </summary>
        /// <param name="taxonPropertyClassID">Initial value of TaxonPropertyClassID.</param>
        public static TaxonPropertyClass CreateTaxonPropertyClass(global::System.Guid taxonPropertyClassID)
        {
            TaxonPropertyClass taxonPropertyClass = new TaxonPropertyClass();
            taxonPropertyClass.TaxonPropertyClassID = taxonPropertyClassID;
            return taxonPropertyClass;
        }
        /// <summary>
        /// There are no comments for Property TaxonPropertyClassID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid TaxonPropertyClassID
        {
            get
            {
                return this._TaxonPropertyClassID;
            }
            set
            {
                this.OnTaxonPropertyClassIDChanging(value);
                this.ReportPropertyChanging("TaxonPropertyClassID");
                this._TaxonPropertyClassID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TaxonPropertyClassID");
                this.OnTaxonPropertyClassIDChanged();
            }
        }
        private global::System.Guid _TaxonPropertyClassID;
        partial void OnTaxonPropertyClassIDChanging(global::System.Guid value);
        partial void OnTaxonPropertyClassIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for TaxonPropertyType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NZOR_System", "FK_TaxonPropertyType_TaxonPropertyClass", "TaxonPropertyType")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<TaxonPropertyType> TaxonPropertyType
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<TaxonPropertyType>("NZOR_System.FK_TaxonPropertyType_TaxonPropertyClass", "TaxonPropertyType");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<TaxonPropertyType>("NZOR_System.FK_TaxonPropertyType_TaxonPropertyClass", "TaxonPropertyType", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for NZOR_System.TaxonPropertyLookup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TaxonPropertyLookupID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NZOR_System", Name="TaxonPropertyLookup")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TaxonPropertyLookup : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TaxonPropertyLookup object.
        /// </summary>
        /// <param name="taxonPropertyLookupID">Initial value of TaxonPropertyLookupID.</param>
        /// <param name="taxonPropertyTypeId">Initial value of TaxonPropertyTypeId.</param>
        public static TaxonPropertyLookup CreateTaxonPropertyLookup(global::System.Guid taxonPropertyLookupID, global::System.Guid taxonPropertyTypeId)
        {
            TaxonPropertyLookup taxonPropertyLookup = new TaxonPropertyLookup();
            taxonPropertyLookup.TaxonPropertyLookupID = taxonPropertyLookupID;
            taxonPropertyLookup.TaxonPropertyTypeId = taxonPropertyTypeId;
            return taxonPropertyLookup;
        }
        /// <summary>
        /// There are no comments for Property TaxonPropertyLookupID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid TaxonPropertyLookupID
        {
            get
            {
                return this._TaxonPropertyLookupID;
            }
            set
            {
                this.OnTaxonPropertyLookupIDChanging(value);
                this.ReportPropertyChanging("TaxonPropertyLookupID");
                this._TaxonPropertyLookupID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TaxonPropertyLookupID");
                this.OnTaxonPropertyLookupIDChanged();
            }
        }
        private global::System.Guid _TaxonPropertyLookupID;
        partial void OnTaxonPropertyLookupIDChanging(global::System.Guid value);
        partial void OnTaxonPropertyLookupIDChanged();
        /// <summary>
        /// There are no comments for Property TaxonPropertyTypeId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid TaxonPropertyTypeId
        {
            get
            {
                return this._TaxonPropertyTypeId;
            }
            set
            {
                this.OnTaxonPropertyTypeIdChanging(value);
                this.ReportPropertyChanging("TaxonPropertyTypeId");
                this._TaxonPropertyTypeId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TaxonPropertyTypeId");
                this.OnTaxonPropertyTypeIdChanged();
            }
        }
        private global::System.Guid _TaxonPropertyTypeId;
        partial void OnTaxonPropertyTypeIdChanging(global::System.Guid value);
        partial void OnTaxonPropertyTypeIdChanged();
        /// <summary>
        /// There are no comments for Property ParentLookupId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.Guid> ParentLookupId
        {
            get
            {
                return this._ParentLookupId;
            }
            set
            {
                this.OnParentLookupIdChanging(value);
                this.ReportPropertyChanging("ParentLookupId");
                this._ParentLookupId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ParentLookupId");
                this.OnParentLookupIdChanged();
            }
        }
        private global::System.Nullable<global::System.Guid> _ParentLookupId;
        partial void OnParentLookupIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnParentLookupIdChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this.ReportPropertyChanging("Value");
                this._Value = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Value");
                this.OnValueChanged();
            }
        }
        private string _Value;
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Property AlternativeStrings in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AlternativeStrings
        {
            get
            {
                return this._AlternativeStrings;
            }
            set
            {
                this.OnAlternativeStringsChanging(value);
                this.ReportPropertyChanging("AlternativeStrings");
                this._AlternativeStrings = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("AlternativeStrings");
                this.OnAlternativeStringsChanged();
            }
        }
        private string _AlternativeStrings;
        partial void OnAlternativeStringsChanging(string value);
        partial void OnAlternativeStringsChanged();
    }
    /// <summary>
    /// There are no comments for NZOR_System.TaxonPropertyType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TaxonPropertyTypeID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NZOR_System", Name="TaxonPropertyType")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TaxonPropertyType : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TaxonPropertyType object.
        /// </summary>
        /// <param name="taxonPropertyTypeID">Initial value of TaxonPropertyTypeID.</param>
        /// <param name="name">Initial value of Name.</param>
        public static TaxonPropertyType CreateTaxonPropertyType(global::System.Guid taxonPropertyTypeID, string name)
        {
            TaxonPropertyType taxonPropertyType = new TaxonPropertyType();
            taxonPropertyType.TaxonPropertyTypeID = taxonPropertyTypeID;
            taxonPropertyType.Name = name;
            return taxonPropertyType;
        }
        /// <summary>
        /// There are no comments for Property TaxonPropertyTypeID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid TaxonPropertyTypeID
        {
            get
            {
                return this._TaxonPropertyTypeID;
            }
            set
            {
                this.OnTaxonPropertyTypeIDChanging(value);
                this.ReportPropertyChanging("TaxonPropertyTypeID");
                this._TaxonPropertyTypeID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TaxonPropertyTypeID");
                this.OnTaxonPropertyTypeIDChanged();
            }
        }
        private global::System.Guid _TaxonPropertyTypeID;
        partial void OnTaxonPropertyTypeIDChanging(global::System.Guid value);
        partial void OnTaxonPropertyTypeIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for TaxonPropertyClass in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NZOR_System", "FK_TaxonPropertyType_TaxonPropertyClass", "TaxonPropertyClass")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public TaxonPropertyClass TaxonPropertyClass
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TaxonPropertyClass>("NZOR_System.FK_TaxonPropertyType_TaxonPropertyClass", "TaxonPropertyClass").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TaxonPropertyClass>("NZOR_System.FK_TaxonPropertyType_TaxonPropertyClass", "TaxonPropertyClass").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for TaxonPropertyClass in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<TaxonPropertyClass> TaxonPropertyClassReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TaxonPropertyClass>("NZOR_System.FK_TaxonPropertyType_TaxonPropertyClass", "TaxonPropertyClass");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<TaxonPropertyClass>("NZOR_System.FK_TaxonPropertyType_TaxonPropertyClass", "TaxonPropertyClass", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for NZOR_System.TaxonRank in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TaxonRankID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NZOR_System", Name="TaxonRank")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TaxonRank : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TaxonRank object.
        /// </summary>
        /// <param name="taxonRankID">Initial value of TaxonRankID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="addedBy">Initial value of AddedBy.</param>
        /// <param name="addedDate">Initial value of AddedDate.</param>
        public static TaxonRank CreateTaxonRank(global::System.Guid taxonRankID, string name, string addedBy, global::System.DateTime addedDate)
        {
            TaxonRank taxonRank = new TaxonRank();
            taxonRank.TaxonRankID = taxonRankID;
            taxonRank.Name = name;
            taxonRank.AddedBy = addedBy;
            taxonRank.AddedDate = addedDate;
            return taxonRank;
        }
        /// <summary>
        /// There are no comments for Property TaxonRankID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid TaxonRankID
        {
            get
            {
                return this._TaxonRankID;
            }
            set
            {
                this.OnTaxonRankIDChanging(value);
                this.ReportPropertyChanging("TaxonRankID");
                this._TaxonRankID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TaxonRankID");
                this.OnTaxonRankIDChanged();
            }
        }
        private global::System.Guid _TaxonRankID;
        partial void OnTaxonRankIDChanging(global::System.Guid value);
        partial void OnTaxonRankIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property KnownAbbreviations in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string KnownAbbreviations
        {
            get
            {
                return this._KnownAbbreviations;
            }
            set
            {
                this.OnKnownAbbreviationsChanging(value);
                this.ReportPropertyChanging("KnownAbbreviations");
                this._KnownAbbreviations = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("KnownAbbreviations");
                this.OnKnownAbbreviationsChanged();
            }
        }
        private string _KnownAbbreviations;
        partial void OnKnownAbbreviationsChanging(string value);
        partial void OnKnownAbbreviationsChanged();
        /// <summary>
        /// There are no comments for Property SortOrder in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> SortOrder
        {
            get
            {
                return this._SortOrder;
            }
            set
            {
                this.OnSortOrderChanging(value);
                this.ReportPropertyChanging("SortOrder");
                this._SortOrder = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SortOrder");
                this.OnSortOrderChanged();
            }
        }
        private global::System.Nullable<int> _SortOrder;
        partial void OnSortOrderChanging(global::System.Nullable<int> value);
        partial void OnSortOrderChanged();
        /// <summary>
        /// There are no comments for Property IncludeInFullName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> IncludeInFullName
        {
            get
            {
                return this._IncludeInFullName;
            }
            set
            {
                this.OnIncludeInFullNameChanging(value);
                this.ReportPropertyChanging("IncludeInFullName");
                this._IncludeInFullName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IncludeInFullName");
                this.OnIncludeInFullNameChanged();
            }
        }
        private global::System.Nullable<bool> _IncludeInFullName;
        partial void OnIncludeInFullNameChanging(global::System.Nullable<bool> value);
        partial void OnIncludeInFullNameChanged();
        /// <summary>
        /// There are no comments for Property AncestorRankID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.Guid> AncestorRankID
        {
            get
            {
                return this._AncestorRankID;
            }
            set
            {
                this.OnAncestorRankIDChanging(value);
                this.ReportPropertyChanging("AncestorRankID");
                this._AncestorRankID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AncestorRankID");
                this.OnAncestorRankIDChanged();
            }
        }
        private global::System.Nullable<global::System.Guid> _AncestorRankID;
        partial void OnAncestorRankIDChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnAncestorRankIDChanged();
        /// <summary>
        /// There are no comments for Property MatchRuleSetID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> MatchRuleSetID
        {
            get
            {
                return this._MatchRuleSetID;
            }
            set
            {
                this.OnMatchRuleSetIDChanging(value);
                this.ReportPropertyChanging("MatchRuleSetID");
                this._MatchRuleSetID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MatchRuleSetID");
                this.OnMatchRuleSetIDChanged();
            }
        }
        private global::System.Nullable<int> _MatchRuleSetID;
        partial void OnMatchRuleSetIDChanging(global::System.Nullable<int> value);
        partial void OnMatchRuleSetIDChanged();
        /// <summary>
        /// There are no comments for Property AddedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AddedBy
        {
            get
            {
                return this._AddedBy;
            }
            set
            {
                this.OnAddedByChanging(value);
                this.ReportPropertyChanging("AddedBy");
                this._AddedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("AddedBy");
                this.OnAddedByChanged();
            }
        }
        private string _AddedBy;
        partial void OnAddedByChanging(string value);
        partial void OnAddedByChanged();
        /// <summary>
        /// There are no comments for Property AddedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime AddedDate
        {
            get
            {
                return this._AddedDate;
            }
            set
            {
                this.OnAddedDateChanging(value);
                this.ReportPropertyChanging("AddedDate");
                this._AddedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AddedDate");
                this.OnAddedDateChanged();
            }
        }
        private global::System.DateTime _AddedDate;
        partial void OnAddedDateChanging(global::System.DateTime value);
        partial void OnAddedDateChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this.ReportPropertyChanging("ModifiedBy");
                this._ModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ModifiedBy");
                this.OnModifiedByChanged();
            }
        }
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    }
}
