//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SystemData", "FK_NameClassProperty_NameClass", "NameClass", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NZOR.Data.SystemData.NameClass), "NameClassProperty", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NZOR.Data.SystemData.NameClassProperty))]

// Original file name:
// Generation date: 9/09/2010 4:17:47 p.m.
namespace NZOR.Data.SystemData
{
    
    /// <summary>
    /// There are no comments for NZOR_System in the schema.
    /// </summary>
    public partial class NZOR_System : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new NZOR_System object using the connection string found in the 'NZOR_System' section of the application configuration file.
        /// </summary>
        public NZOR_System() : 
                base("name=NZOR_System", "NZOR_System")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new NZOR_System object.
        /// </summary>
        public NZOR_System(string connectionString) : 
                base(connectionString, "NZOR_System")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new NZOR_System object.
        /// </summary>
        public NZOR_System(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "NZOR_System")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for ConceptRelationshipType in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ConceptRelationshipType> ConceptRelationshipType
        {
            get
            {
                if ((this._ConceptRelationshipType == null))
                {
                    this._ConceptRelationshipType = base.CreateQuery<ConceptRelationshipType>("[ConceptRelationshipType]");
                }
                return this._ConceptRelationshipType;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ConceptRelationshipType> _ConceptRelationshipType;
        /// <summary>
        /// There are no comments for TaxonRank in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<TaxonRank> TaxonRank
        {
            get
            {
                if ((this._TaxonRank == null))
                {
                    this._TaxonRank = base.CreateQuery<TaxonRank>("[TaxonRank]");
                }
                return this._TaxonRank;
            }
        }
        private global::System.Data.Objects.ObjectQuery<TaxonRank> _TaxonRank;
        /// <summary>
        /// There are no comments for NameClass in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<NameClass> NameClass
        {
            get
            {
                if ((this._NameClass == null))
                {
                    this._NameClass = base.CreateQuery<NameClass>("[NameClass]");
                }
                return this._NameClass;
            }
        }
        private global::System.Data.Objects.ObjectQuery<NameClass> _NameClass;
        /// <summary>
        /// There are no comments for NameClassProperty in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<NameClassProperty> NameClassProperty
        {
            get
            {
                if ((this._NameClassProperty == null))
                {
                    this._NameClassProperty = base.CreateQuery<NameClassProperty>("[NameClassProperty]");
                }
                return this._NameClassProperty;
            }
        }
        private global::System.Data.Objects.ObjectQuery<NameClassProperty> _NameClassProperty;
        /// <summary>
        /// There are no comments for ConceptRelationshipType in the schema.
        /// </summary>
        public void AddToConceptRelationshipType(ConceptRelationshipType conceptRelationshipType)
        {
            base.AddObject("ConceptRelationshipType", conceptRelationshipType);
        }
        /// <summary>
        /// There are no comments for TaxonRank in the schema.
        /// </summary>
        public void AddToTaxonRank(TaxonRank taxonRank)
        {
            base.AddObject("TaxonRank", taxonRank);
        }
        /// <summary>
        /// There are no comments for NameClass in the schema.
        /// </summary>
        public void AddToNameClass(NameClass nameClass)
        {
            base.AddObject("NameClass", nameClass);
        }
        /// <summary>
        /// There are no comments for NameClassProperty in the schema.
        /// </summary>
        public void AddToNameClassProperty(NameClassProperty nameClassProperty)
        {
            base.AddObject("NameClassProperty", nameClassProperty);
        }
    }
    /// <summary>
    /// There are no comments for SystemData.ConceptRelationshipType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ConceptRelationshipTypeID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SystemData", Name="ConceptRelationshipType")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ConceptRelationshipType : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ConceptRelationshipType object.
        /// </summary>
        /// <param name="conceptRelationshipTypeID">Initial value of ConceptRelationshipTypeID.</param>
        /// <param name="relationship">Initial value of Relationship.</param>
        public static ConceptRelationshipType CreateConceptRelationshipType(global::System.Guid conceptRelationshipTypeID, string relationship)
        {
            ConceptRelationshipType conceptRelationshipType = new ConceptRelationshipType();
            conceptRelationshipType.ConceptRelationshipTypeID = conceptRelationshipTypeID;
            conceptRelationshipType.Relationship = relationship;
            return conceptRelationshipType;
        }
        /// <summary>
        /// There are no comments for Property ConceptRelationshipTypeID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ConceptRelationshipTypeID
        {
            get
            {
                return this._ConceptRelationshipTypeID;
            }
            set
            {
                this.OnConceptRelationshipTypeIDChanging(value);
                this.ReportPropertyChanging("ConceptRelationshipTypeID");
                this._ConceptRelationshipTypeID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ConceptRelationshipTypeID");
                this.OnConceptRelationshipTypeIDChanged();
            }
        }
        private global::System.Guid _ConceptRelationshipTypeID;
        partial void OnConceptRelationshipTypeIDChanging(global::System.Guid value);
        partial void OnConceptRelationshipTypeIDChanged();
        /// <summary>
        /// There are no comments for Property Relationship in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Relationship
        {
            get
            {
                return this._Relationship;
            }
            set
            {
                this.OnRelationshipChanging(value);
                this.ReportPropertyChanging("Relationship");
                this._Relationship = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Relationship");
                this.OnRelationshipChanged();
            }
        }
        private string _Relationship;
        partial void OnRelationshipChanging(string value);
        partial void OnRelationshipChanged();
        /// <summary>
        /// There are no comments for Property MinOccurences in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> MinOccurences
        {
            get
            {
                return this._MinOccurences;
            }
            set
            {
                this.OnMinOccurencesChanging(value);
                this.ReportPropertyChanging("MinOccurences");
                this._MinOccurences = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MinOccurences");
                this.OnMinOccurencesChanged();
            }
        }
        private global::System.Nullable<int> _MinOccurences;
        partial void OnMinOccurencesChanging(global::System.Nullable<int> value);
        partial void OnMinOccurencesChanged();
        /// <summary>
        /// There are no comments for Property MaxOccurrences in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> MaxOccurrences
        {
            get
            {
                return this._MaxOccurrences;
            }
            set
            {
                this.OnMaxOccurrencesChanging(value);
                this.ReportPropertyChanging("MaxOccurrences");
                this._MaxOccurrences = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MaxOccurrences");
                this.OnMaxOccurrencesChanged();
            }
        }
        private global::System.Nullable<int> _MaxOccurrences;
        partial void OnMaxOccurrencesChanging(global::System.Nullable<int> value);
        partial void OnMaxOccurrencesChanged();
    }
    /// <summary>
    /// There are no comments for SystemData.TaxonRank in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TaxonRankID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SystemData", Name="TaxonRank")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TaxonRank : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TaxonRank object.
        /// </summary>
        /// <param name="taxonRankID">Initial value of TaxonRankID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="addedBy">Initial value of AddedBy.</param>
        /// <param name="addedDate">Initial value of AddedDate.</param>
        public static TaxonRank CreateTaxonRank(global::System.Guid taxonRankID, string name, string addedBy, global::System.DateTime addedDate)
        {
            TaxonRank taxonRank = new TaxonRank();
            taxonRank.TaxonRankID = taxonRankID;
            taxonRank.Name = name;
            taxonRank.AddedBy = addedBy;
            taxonRank.AddedDate = addedDate;
            return taxonRank;
        }
        /// <summary>
        /// There are no comments for Property TaxonRankID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid TaxonRankID
        {
            get
            {
                return this._TaxonRankID;
            }
            set
            {
                this.OnTaxonRankIDChanging(value);
                this.ReportPropertyChanging("TaxonRankID");
                this._TaxonRankID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TaxonRankID");
                this.OnTaxonRankIDChanged();
            }
        }
        private global::System.Guid _TaxonRankID;
        partial void OnTaxonRankIDChanging(global::System.Guid value);
        partial void OnTaxonRankIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property KnownAbbreviations in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string KnownAbbreviations
        {
            get
            {
                return this._KnownAbbreviations;
            }
            set
            {
                this.OnKnownAbbreviationsChanging(value);
                this.ReportPropertyChanging("KnownAbbreviations");
                this._KnownAbbreviations = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("KnownAbbreviations");
                this.OnKnownAbbreviationsChanged();
            }
        }
        private string _KnownAbbreviations;
        partial void OnKnownAbbreviationsChanging(string value);
        partial void OnKnownAbbreviationsChanged();
        /// <summary>
        /// There are no comments for Property SortOrder in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> SortOrder
        {
            get
            {
                return this._SortOrder;
            }
            set
            {
                this.OnSortOrderChanging(value);
                this.ReportPropertyChanging("SortOrder");
                this._SortOrder = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SortOrder");
                this.OnSortOrderChanged();
            }
        }
        private global::System.Nullable<int> _SortOrder;
        partial void OnSortOrderChanging(global::System.Nullable<int> value);
        partial void OnSortOrderChanged();
        /// <summary>
        /// There are no comments for Property IncludeInFullName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> IncludeInFullName
        {
            get
            {
                return this._IncludeInFullName;
            }
            set
            {
                this.OnIncludeInFullNameChanging(value);
                this.ReportPropertyChanging("IncludeInFullName");
                this._IncludeInFullName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IncludeInFullName");
                this.OnIncludeInFullNameChanged();
            }
        }
        private global::System.Nullable<bool> _IncludeInFullName;
        partial void OnIncludeInFullNameChanging(global::System.Nullable<bool> value);
        partial void OnIncludeInFullNameChanged();
        /// <summary>
        /// There are no comments for Property AncestorRankID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.Guid> AncestorRankID
        {
            get
            {
                return this._AncestorRankID;
            }
            set
            {
                this.OnAncestorRankIDChanging(value);
                this.ReportPropertyChanging("AncestorRankID");
                this._AncestorRankID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AncestorRankID");
                this.OnAncestorRankIDChanged();
            }
        }
        private global::System.Nullable<global::System.Guid> _AncestorRankID;
        partial void OnAncestorRankIDChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnAncestorRankIDChanged();
        /// <summary>
        /// There are no comments for Property MatchRuleSetID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> MatchRuleSetID
        {
            get
            {
                return this._MatchRuleSetID;
            }
            set
            {
                this.OnMatchRuleSetIDChanging(value);
                this.ReportPropertyChanging("MatchRuleSetID");
                this._MatchRuleSetID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MatchRuleSetID");
                this.OnMatchRuleSetIDChanged();
            }
        }
        private global::System.Nullable<int> _MatchRuleSetID;
        partial void OnMatchRuleSetIDChanging(global::System.Nullable<int> value);
        partial void OnMatchRuleSetIDChanged();
        /// <summary>
        /// There are no comments for Property AddedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AddedBy
        {
            get
            {
                return this._AddedBy;
            }
            set
            {
                this.OnAddedByChanging(value);
                this.ReportPropertyChanging("AddedBy");
                this._AddedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("AddedBy");
                this.OnAddedByChanged();
            }
        }
        private string _AddedBy;
        partial void OnAddedByChanging(string value);
        partial void OnAddedByChanged();
        /// <summary>
        /// There are no comments for Property AddedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime AddedDate
        {
            get
            {
                return this._AddedDate;
            }
            set
            {
                this.OnAddedDateChanging(value);
                this.ReportPropertyChanging("AddedDate");
                this._AddedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AddedDate");
                this.OnAddedDateChanged();
            }
        }
        private global::System.DateTime _AddedDate;
        partial void OnAddedDateChanging(global::System.DateTime value);
        partial void OnAddedDateChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this.ReportPropertyChanging("ModifiedBy");
                this._ModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ModifiedBy");
                this.OnModifiedByChanged();
            }
        }
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    }
    /// <summary>
    /// There are no comments for SystemData.NameClass in the schema.
    /// </summary>
    /// <KeyProperties>
    /// NameClassID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SystemData", Name="NameClass")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class NameClass : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new NameClass object.
        /// </summary>
        /// <param name="nameClassID">Initial value of NameClassID.</param>
        /// <param name="title">Initial value of Title.</param>
        public static NameClass CreateNameClass(global::System.Guid nameClassID, string title)
        {
            NameClass nameClass = new NameClass();
            nameClass.NameClassID = nameClassID;
            nameClass.Title = title;
            return nameClass;
        }
        /// <summary>
        /// There are no comments for Property NameClassID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid NameClassID
        {
            get
            {
                return this._NameClassID;
            }
            set
            {
                this.OnNameClassIDChanging(value);
                this.ReportPropertyChanging("NameClassID");
                this._NameClassID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NameClassID");
                this.OnNameClassIDChanged();
            }
        }
        private global::System.Guid _NameClassID;
        partial void OnNameClassIDChanging(global::System.Guid value);
        partial void OnNameClassIDChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for NameClassProperty in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SystemData", "FK_NameClassProperty_NameClass", "NameClassProperty")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<NameClassProperty> NameClassProperty
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<NameClassProperty>("SystemData.FK_NameClassProperty_NameClass", "NameClassProperty");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<NameClassProperty>("SystemData.FK_NameClassProperty_NameClass", "NameClassProperty", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SystemData.NameClassProperty in the schema.
    /// </summary>
    /// <KeyProperties>
    /// NameClassPropertyID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SystemData", Name="NameClassProperty")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class NameClassProperty : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new NameClassProperty object.
        /// </summary>
        /// <param name="nameClassPropertyID">Initial value of NameClassPropertyID.</param>
        public static NameClassProperty CreateNameClassProperty(global::System.Guid nameClassPropertyID)
        {
            NameClassProperty nameClassProperty = new NameClassProperty();
            nameClassProperty.NameClassPropertyID = nameClassPropertyID;
            return nameClassProperty;
        }
        /// <summary>
        /// There are no comments for Property NameClassPropertyID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid NameClassPropertyID
        {
            get
            {
                return this._NameClassPropertyID;
            }
            set
            {
                this.OnNameClassPropertyIDChanging(value);
                this.ReportPropertyChanging("NameClassPropertyID");
                this._NameClassPropertyID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NameClassPropertyID");
                this.OnNameClassPropertyIDChanged();
            }
        }
        private global::System.Guid _NameClassPropertyID;
        partial void OnNameClassPropertyIDChanging(global::System.Guid value);
        partial void OnNameClassPropertyIDChanged();
        /// <summary>
        /// There are no comments for Property PropertyName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyName
        {
            get
            {
                return this._PropertyName;
            }
            set
            {
                this.OnPropertyNameChanging(value);
                this.ReportPropertyChanging("PropertyName");
                this._PropertyName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PropertyName");
                this.OnPropertyNameChanged();
            }
        }
        private string _PropertyName;
        partial void OnPropertyNameChanging(string value);
        partial void OnPropertyNameChanged();
        /// <summary>
        /// There are no comments for Property PropertyType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyType
        {
            get
            {
                return this._PropertyType;
            }
            set
            {
                this.OnPropertyTypeChanging(value);
                this.ReportPropertyChanging("PropertyType");
                this._PropertyType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PropertyType");
                this.OnPropertyTypeChanged();
            }
        }
        private string _PropertyType;
        partial void OnPropertyTypeChanging(string value);
        partial void OnPropertyTypeChanged();
        /// <summary>
        /// There are no comments for Property MinOccurrences in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> MinOccurrences
        {
            get
            {
                return this._MinOccurrences;
            }
            set
            {
                this.OnMinOccurrencesChanging(value);
                this.ReportPropertyChanging("MinOccurrences");
                this._MinOccurrences = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MinOccurrences");
                this.OnMinOccurrencesChanged();
            }
        }
        private global::System.Nullable<int> _MinOccurrences;
        partial void OnMinOccurrencesChanging(global::System.Nullable<int> value);
        partial void OnMinOccurrencesChanged();
        /// <summary>
        /// There are no comments for Property MaxOccurrences in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> MaxOccurrences
        {
            get
            {
                return this._MaxOccurrences;
            }
            set
            {
                this.OnMaxOccurrencesChanging(value);
                this.ReportPropertyChanging("MaxOccurrences");
                this._MaxOccurrences = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MaxOccurrences");
                this.OnMaxOccurrencesChanged();
            }
        }
        private global::System.Nullable<int> _MaxOccurrences;
        partial void OnMaxOccurrencesChanging(global::System.Nullable<int> value);
        partial void OnMaxOccurrencesChanged();
        /// <summary>
        /// There are no comments for Property GoverningCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string GoverningCode
        {
            get
            {
                return this._GoverningCode;
            }
            set
            {
                this.OnGoverningCodeChanging(value);
                this.ReportPropertyChanging("GoverningCode");
                this._GoverningCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("GoverningCode");
                this.OnGoverningCodeChanged();
            }
        }
        private string _GoverningCode;
        partial void OnGoverningCodeChanging(string value);
        partial void OnGoverningCodeChanged();
        /// <summary>
        /// There are no comments for NameClass in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SystemData", "FK_NameClassProperty_NameClass", "NameClass")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public NameClass NameClass
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<NameClass>("SystemData.FK_NameClassProperty_NameClass", "NameClass").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<NameClass>("SystemData.FK_NameClassProperty_NameClass", "NameClass").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for NameClass in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<NameClass> NameClassReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<NameClass>("SystemData.FK_NameClassProperty_NameClass", "NameClass");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<NameClass>("SystemData.FK_NameClassProperty_NameClass", "NameClass", value);
                }
            }
        }
    }
}
