INSERT INTO [provider].[TaxonProperty]
           ([TaxonPropertyID]
           ,[TaxonPropertyClassID]
           ,[ConsensusTaxonPropertyID]
           ,[LinkStatus]
           ,[MatchScore]
           ,[ProviderRecordID]
           ,[ProviderReferenceID]
           ,[ReferenceID]
           ,[ConceptID]
           ,[ProviderNameID]
           ,[ProviderConceptID]
           ,[NameID]
           ,[DataSourceID]
           ,[InUse]
           ,[ProviderCreatedDate]
           ,[ProviderModifiedDate]
           ,[AddedDate]
		   ,[ModifiedDate])
     VALUES
           (@taxonPropertyId,
		    @taxonPropertyClassId,
			@consensusTaxonPropertyId,
			@linkStatus,
			@matchScore,
			@providerRecordId,
			@providerReferenceId,
			@referenceId,
			@conceptId,
			@providerNameId,
			@providerConceptId,
			@nameId,
			@dataSourceId,
			@inUse,
			@providerCreatedDate,
			@providerModifiedDate,
			@addedDate,
			@modifiedDate)