select [NameRequestId]
	   ,[FullName]
       ,[RequestDate]
       ,[ApiKey]
	   ,[BatchMatchId]
       ,[RequesterEmail]
	   ,[ExternalLookupServiceId]
	   ,[ExternalLookupDataUrl]
       ,[Status]
       ,[AddedDate]
       ,[AddedBy]
       ,[ModifiedDate]
       ,[ModifiedBy]
from [admin].[NameRequest]
where FullName = @FullName