INSERT INTO [admin].[NameRequest]
           ([NameRequestId]
		   ,[FullName]
           ,[RequestDate]
           ,[ApiKey]
		   ,[BatchMatchId]
           ,[RequesterEmail]
	       ,[ExternalLookupServiceId]
	       ,[ExternalLookupDataUrl]
           ,[Status]
           ,[AddedDate]
           ,[AddedBy]
           ,[ModifiedDate]
           ,[ModifiedBy])
     VALUES
           (@NameRequestId
		   ,@FullName
           ,@RequestDate
           ,@ApiKey
		   ,@BatchMatchId
           ,@RequesterEmail
		   ,@ExternalLookupServiceId
	       ,@ExternalLookupDataUrl
           ,@Status
           ,@AddedDate
           ,@AddedBy
           ,@ModifiedDate
           ,@ModifiedBy)
