CREATE TABLE 
	[dbo].[GeoRegion]
	(
	GeoRegionID UNIQUEIDENTIFIER NOT NULL, 
	
	GeographicSchemaID UNIQUEIDENTIFIER NOT NULL,
	CorrectGeoRegionID UNIQUEIDENTIFIER NULL, 
	ParentGeoRegionID UNIQUEIDENTIFIER NULL,

	Name NVARCHAR(500) NOT NULL, 
	Language NVARCHAR(50) NULL
	)
