CREATE TABLE 
	[consensus].StackedName
	(
	StackedNameID UNIQUEIDENTIFIER NOT NULL,

	SeedNameID UNIQUEIDENTIFIER NOT NULL,
	AccordingToID UNIQUEIDENTIFIER NULL,
	NameID UNIQUEIDENTIFIER NOT NULL, 
	TaxonRankID UNIQUEIDENTIFIER NULL, 
	
	CanonicalName NVARCHAR(250) NOT NULL, 
	RankName NVARCHAR(100) NOT NULL, 
	SortOrder INT NULL, 
	Depth INT NULL
)
