ALTER TABLE [admin].[AttachmentPoint]
    ADD CONSTRAINT [prkAttachmentPoint] PRIMARY KEY CLUSTERED ([AttachmentPointID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

