ALTER TABLE [admin].[Provider]
    ADD CONSTRAINT [prkProvider] PRIMARY KEY CLUSTERED ([ProviderID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

